import React, { useState, useEffect } from 'react';
import MapComponent from './components/MapComponent';
import Sidebar from './components/Sidebar';
import { getAvailableDates, parseStationData } from './utils/dataParser';
import { StationLocation, RawDataEntry } from './types';
import { RAW_DATA as STATIC_DATA } from './constants';
import { Menu } from 'lucide-react';

function App() {
  const [dates, setDates] = useState<string[]>([]);
  const [selectedDate, setSelectedDate] = useState<string>('');
  const [stations, setStations] = useState<StationLocation[]>([]);
  const [selectedStation, setSelectedStation] = useState<StationLocation | null>(null);
  const [isSidebarOpen, setSidebarOpen] = useState(true);
  const [isLoading, setIsLoading] = useState(true); // Track loading state

  // Combine static fallback data with potential fetched data
  const [allData, setAllData] = useState<RawDataEntry[]>(STATIC_DATA);

  // Initial Load: Fetch external data (generated by scraper) and merge
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        // Attempt to fetch the JSON generated by the Python script
        // This path corresponds to public/data/irsa_river_data.json
        const response = await fetch('/data/irsa_river_data.json');
        if (response.ok) {
          const fetchedData: RawDataEntry[] = await response.json();
          console.log("Loaded external data:", fetchedData.length, "entries");

          // Merge: Prefer fetched data, fallback to static if not present
          setAllData([...fetchedData, ...STATIC_DATA]);
        } else {
          console.log("External data not found, using static data.");
          setAllData(STATIC_DATA);
        }
      } catch (error) {
        console.warn("Failed to fetch external data, using static fallback:", error);
        setAllData(STATIC_DATA);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, []);

  // Update Dates list when data changes
  useEffect(() => {
    const available = getAvailableDates(allData);
    setDates(available);
    if (available.length > 0 && !selectedDate) {
      setSelectedDate(available[0]); // Select most recent if none selected
    } else if (available.length > 0 && selectedDate && !available.includes(selectedDate)) {
      setSelectedDate(available[0]); // Reset if selected date no longer exists
    }
  }, [allData, selectedDate]);

  // Update stations when date changes
  useEffect(() => {
    if (selectedDate && !isLoading) {
      const data = parseStationData(selectedDate, allData);
      console.log("Parsed stations for", selectedDate, ":", data);
      setStations(data);

      // If a station was selected, try to update its data for the new date
      if (selectedStation) {
        const updatedStation = data.find(s => s.id === selectedStation.id);
        if (updatedStation) {
          setSelectedStation(updatedStation);
        }
      }
    }
  }, [selectedDate, allData, isLoading]);

  const handleStationSelect = (station: StationLocation) => {
    setSelectedStation(station);
    setSidebarOpen(true);
  };

  return (
    <div className="relative w-full h-screen bg-gray-100 overflow-hidden flex">

      {/* Mobile Sidebar Toggle */}
      {!isSidebarOpen && (
        <button
          onClick={() => setSidebarOpen(true)}
          className="absolute top-4 right-4 z-[999] bg-white p-2 rounded-md shadow-lg hover:bg-gray-50 text-gray-700"
        >
          <Menu className="w-6 h-6" />
        </button>
      )}

      {/* Main Map Area */}
      <div className={`flex-1 relative h-full transition-all duration-300 ${isSidebarOpen ? 'mr-0 md:mr-96' : 'mr-0'}`}>
        {isLoading ? (
          <div className="w-full h-full flex items-center justify-center bg-gray-50">
            <div className="text-center">
              <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
              <p className="text-gray-600 font-semibold">Loading river data...</p>
            </div>
          </div>
        ) : (
          <MapComponent
            stations={stations}
            onStationSelect={handleStationSelect}
            selectedStationId={selectedStation?.id || null}
          />
        )}

        {/* Date Badge Overlay on Map */}
        {!isLoading && (
          <div className="absolute top-4 left-4 z-[400] bg-white/90 backdrop-blur-sm px-4 py-2 rounded-lg shadow-md border-l-4 border-blue-600">
            <p className="text-xs text-gray-500 font-semibold uppercase">Current View</p>
            <p className="text-lg font-bold text-gray-900">{selectedDate || 'Loading...'}</p>
          </div>
        )}
      </div>

      {/* Sidebar */}
      <div className={`fixed inset-y-0 right-0 w-full md:w-96 z-[1000] transform transition-transform duration-300 ease-in-out ${isSidebarOpen ? 'translate-x-0' : 'translate-x-full'}`}>
        <Sidebar
          station={selectedStation}
          onClose={() => setSidebarOpen(false)}
          dateList={dates}
          selectedDate={selectedDate}
          onDateChange={setSelectedDate}
        />
      </div>
    </div>
  );
}

export default App;
